# Site settings
title: "Viraj Joshi"
description: "Personal website of Viraj Joshi"
url: "https://viraj-joshi.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
future: true
permalink: /blog/:year/:month/:day/:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - README.md

# Include
include:
  - _pages

# Author
author: "Viraj Joshi"
email: "viraj_joshi@utexas.edu"